In [3]:
pip install tensorflow

  Using cached absl_py-2.2.2-py3-none-any.whl.metadata (2.6 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
  Using cached tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 1.3/376.0 MB 6.7 MB/s eta 0:00:56
   ---------------------------------------- 2.6/376.0 MB 6.6 MB/s eta 0:00:57
   ---------------------------------------- 3.9/376.0 MB 6.3 MB/s eta 

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
## Sententeces
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [7]:
# Define the vocabular size
vocab_size = 10000

In [11]:
# One hot representation
# One-hot encoding is a technique used to convert categorical data into a format that can be processed by
# machine learning algorithms. It works by creating a new column for each category in the data, and
# assigning a 1 or 0 to each row depending on whether the row belongs to the category

one_hot_repr = [one_hot(i,vocab_size) for i in sent]
one_hot_repr

[[9764, 3077, 6690, 3333],
 [9764, 3077, 6690, 1912],
 [9764, 8200, 6690, 9444],
 [9330, 3516, 7459, 1662, 907],
 [9330, 3516, 7459, 1662, 4564],
 [3169, 9764, 2669, 6690, 1588],
 [9671, 7598, 6353, 1662]]

In [14]:
# Word Embedding Representation
# ==============================
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
# The length of the sentences in the sent variable are not constant, to make it constant we do pad_sequence
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

# padding = 'pre' means, the padding will be done from the left side of the sentence, maxlen = 8 means,
# the length of the sentence will be 8. if padding set to 'post', the padding will be done from the right side of the sentence.

# Now the length of the embedded_docs is constant
print(embedded_docs)

[[   0    0    0    0 9764 3077 6690 3333]
 [   0    0    0    0 9764 3077 6690 1912]
 [   0    0    0    0 9764 8200 6690 9444]
 [   0    0    0 9330 3516 7459 1662  907]
 [   0    0    0 9330 3516 7459 1662 4564]
 [   0    0    0 3169 9764 2669 6690 1588]
 [   0    0    0    0 9671 7598 6353 1662]]


In [16]:
# Feature representation
dim = 10

In [18]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam','mse')

c:\Users\DELL\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 523ms/step


array([[[-0.01636187, -0.01171   ,  0.0414528 , -0.00465622,
          0.03513094, -0.02040564, -0.02864522,  0.04363995,
          0.04895959, -0.03355552],
        [-0.01636187, -0.01171   ,  0.0414528 , -0.00465622,
          0.03513094, -0.02040564, -0.02864522,  0.04363995,
          0.04895959, -0.03355552],
        [-0.01636187, -0.01171   ,  0.0414528 , -0.00465622,
          0.03513094, -0.02040564, -0.02864522,  0.04363995,
          0.04895959, -0.03355552],
        [-0.01636187, -0.01171   ,  0.0414528 , -0.00465622,
          0.03513094, -0.02040564, -0.02864522,  0.04363995,
          0.04895959, -0.03355552],
        [ 0.04349371,  0.03057522, -0.03666326,  0.03167571,
          0.00975544, -0.04143808,  0.02863218,  0.04057642,
          0.04427404,  0.0011586 ],
        [ 0.03280786, -0.0428683 , -0.04680184,  0.02224845,
         -0.04694275, -0.04357157, -0.03090893, -0.01182027,
         -0.03756322, -0.03776542],
        [ 0.00413704,  0.04685182, -0.03035638, -0.0

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)